// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"graphqltest/models"
)

type Auth struct {
	User  *models.User `json:"user"`
	Token string       `json:"token"`
}

type GetUser struct {
	ID string `json:"id"`
}

type NewUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}
